# Generated by Django 4.2.5 on 2023-09-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration_video',
            field=models.IntegerField(verbose_name='video duration in seconds'),
        ),
    ]
