# Generated by Django 4.2.5 on 2023-09-22 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_duration_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonviewstudent',
            old_name='viewing_time',
            new_name='viewing_datetime',
        ),
        migrations.AddField(
            model_name='lessonviewstudent',
            name='viewing_in_seconds',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_video',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='video duration in seconds'),
        ),
    ]
