# Generated by Django 4.2.5 on 2023-09-22 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_rename_viewing_time_lessonviewstudent_viewing_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonviewstudent',
            name='viewing_in_seconds',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
